apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    app.kubernetes.io/component: database
    {{- if .Values.environment }}
    environment: {{ .Values.environment | quote }}
    {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
