apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: todo-app
    component: backend
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: todo-app
    component: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
