apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-demo

resources:
  - namespace.yaml
  - ../../base
  - secret.yaml

patches:
  - path: patch-replicas.yaml
  - path: patch-configmap.yaml

labels:
  - pairs:
      environment: dev
    includeSelectors: false
